version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: db_mascotas
     volumes:
       - db_data:/var/lib/mysql    
     restart: always
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
     env_file:
       - ./env.dev

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wp_mascotas
     ports:
       - "8000:80"    
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

   grafana:
     image: grafana/grafana:5.1.0
     container_name: gr_mascotas
     volumes:
       - ./grafana-storage:/var/lib/grafana
     ports:
       - "3000:3000"
     user: "104"
     environment:
       GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:/grafana"

   nginx:
    image: nginx:latest
    container_name: nginx_mascotas
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
      - grafana 
    ports:
      - "4000:4000"

volumes:
    db_data: {}
